name: 

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version:
          - "8"
          - "11"
          - "17"
        java-distribution:
          - adopt
          
    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ java-distribution }} JDK ${{ java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ java-version }}
          distribution: ${{ java-distribution }}
      - name: Build with Maven
        run: mvn -B clean package verify
