name: Build Commit

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18" ]

    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: ./build-in-docker.sh openjdk:${{matrix.java-version}} -B -T3 clean verify
