name: Build Commit

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image:
          - openjdk:8-alpine
          - openjdk:9-alpine
          - openjdk:10-alpine
          - openjdk:11-alpine
          - openjdk:12-alpine
          - openjdk:13-alpine
          - openjdk:14-alpine
          - openjdk:15-alpine
          - openjdk:16-alpine
          - openjdk:17-alpine
          - openjdk:18-alpine
          - openjdk:19          # no alpine, yet!
          

    steps:
      - uses: actions/checkout@v2
      - name: Build with Maven
        run: ./build-in-docker.sh "${{matrix.image}}" -B -T3 clean verify
