name: Ensure the commit builds

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version:
          - "8"
          - "11"
          - "17"
        java-distribution:
          - adopt
          
    steps:
      - uses: actions/checkout@v2
      - name: Set up ${{ matrix.java-distribution }} JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}
      - name: Build with Maven
        run: ./mvnw -B clean package verify
